In [1]:
import pandas as pd

In [2]:
import numpy as np

In [73]:
df=pd.read_csv("train-3.csv")
df

,id,publish_date,weekday,channel,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,target
0,0,2013-01-07,Monday,Entertainment,12.0,219.0,0.663594,1.0,0.815385,4.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,0
1,1,2013-01-07,Monday,Business,9.0,255.0,0.604743,1.0,0.791946,3.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,0
2,2,2013-01-07,Monday,Business,9.0,211.0,0.575130,1.0,0.663866,3.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1
3,3,2013-01-07,Monday,Entertainment,9.0,531.0,0.503788,1.0,0.665635,9.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,0
4,4,2013-01-07,Monday,Tech,13.0,1072.0,0.415646,1.0,0.540890,19.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31710,31710,2014-08-28,Friday,Other,11.0,167.0,0.568493,1.0,0.575472,23.0,...,0.100000,0.8,-0.281731,-0.500,-0.050000,0.650000,0.350000,0.150000,0.350000,1
31711,31711,2014-08-28,Friday,Business,12.0,795.0,0.465736,1.0,0.623246,23.0,...,0.062500,0.9,-0.223264,-0.400,-0.050000,0.000000,0.000000,0.500000,0.000000,1
31712,31712,2014-08-28,Friday,Tech,13.0,1018.0,0.453823,1.0,0.631491,10.0,...,0.050000,0.9,-0.239074,-0.600,-0.050000,0.100000,0.000000,0.400000,0.000000,1
31713,31713,2014-08-28,Friday,Tech,10.0,190.0,0.609626,1.0,0.774775,2.0,...,0.100000,1.0,-1.000000,-1.000,-1.000000,0.000000,0.000000,0.500000,0.000000,1
31714,31714,2014-08-28,Friday,Social Media,12.0,1052.0,0.364971,1.0,0.507488,6.0,...,0.100000,1.0,-0.226603,-0.500,-0.125000,0.485000,0.090000,0.015000,0.090000,1

In [7]:
df.head()

,id,publish_date,weekday,channel,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,target
0,0,2013-01-07,Monday,Entertainment,12.0,219.0,0.663594,1.0,0.815385,4.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,0
1,1,2013-01-07,Monday,Business,9.0,255.0,0.604743,1.0,0.791946,3.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,0
2,2,2013-01-07,Monday,Business,9.0,211.0,0.575130,1.0,0.663866,3.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1
3,3,2013-01-07,Monday,Entertainment,9.0,531.0,0.503788,1.0,0.665635,9.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,0
4,4,2013-01-07,Monday,Tech,13.0,1072.0,0.415646,1.0,0.540890,19.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,0

In [8]:
df.shape

(31715, 49)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31715 entries, 0 to 31714
Data columns (total 49 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            31715 non-null  int64
 1   publish_date                  31715 non-null  object
 2   weekday                       31715 non-null  object
 3   channel                       31715 non-null  object
 4   n_tokens_title                31715 non-null  float64
 5   n_tokens_content              31715 non-null  float64
 6   n_unique_tokens               31715 non-null  float64
 7   n_non_stop_words              31715 non-null  float64
 8   n_non_stop_unique_tokens      31715 non-null  float64
 9   num_hrefs                     31715 non-null  float64
 10  num_self_hrefs                31715 non-null  float64
 11  num_imgs                      31715 non-null  float64
 12  num_videos                    31715 non-null  float64
 13  average_token_length          31715 non-null  float64
 14  num_keywords                  31715 non-null  float64
 15  kw_min_min                    31715 non-null  float64
 16  kw_max_min                    31715 non-null  float64
 17  kw_avg_min                    31715 non-null  float64
 18  kw_min_max                    31715 non-null  float64
 19  kw_max_max                    31715 non-null  float64
 20  kw_avg_max                    31715 non-null  float64
 21  kw_min_avg                    31715 non-null  float64
 22  kw_max_avg                    31715 non-null  float64
 23  kw_avg_avg                    31715 non-null  float64
 24  self_reference_min_shares     31715 non-null  float64
 25  self_reference_max_shares     31715 non-null  float64
 26  self_reference_avg_shares     31715 non-null  float64
 27  LDA_00                        31715 non-null  float64
 28  LDA_01                        31715 non-null  float64
 29  LDA_02                        31715 non-null  float64
 30  LDA_03                        31715 non-null  float64
 31  LDA_04                        31715 non-null  float64
 32  global_subjectivity           31715 non-null  float64
 33  global_sentiment_polarity     31715 non-null  float64
 34  global_rate_positive_words    31715 non-null  float64
 35  global_rate_negative_words    31715 non-null  float64
 36  rate_positive_words           31715 non-null  float64
 37  rate_negative_words           31715 non-null  float64
 38  avg_positive_polarity         31715 non-null  float64
 39  min_positive_polarity         31715 non-null  float64
 40  max_positive_polarity         31715 non-null  float64
 41  avg_negative_polarity         31715 non-null  float64
 42  min_negative_polarity         31715 non-null  float64
 43  max_negative_polarity         31715 non-null  float64
 44  title_subjectivity            31715 non-null  float64
 45  title_sentiment_polarity      31715 non-null  float64
 46  abs_title_subjectivity        31715 non-null  float64
 47  abs_title_sentiment_polarity  31715 non-null  float64
 48  target                        31715 non-null  int64
dtypes: float64(44), int64(2), object(3)
memory usage: 11.9+ MB

In [10]:
df.isnull().sum()

id                              0
publish_date                    0
weekday                         0
channel                         0
n_tokens_title                  0
n_tokens_content                0
n_unique_tokens                 0
n_non_stop_words                0
n_non_stop_unique_tokens        0
num_hrefs                       0
num_self_hrefs                  0
num_imgs                        0
num_videos                      0
average_token_length            0
num_keywords                    0
kw_min_min                      0
kw_max_min                      0
kw_avg_min                      0
kw_min_max                      0
kw_max_max                      0
kw_avg_max                      0
kw_min_avg                      0
kw_max_avg                      0
kw_avg_avg                      0
self_reference_min_shares       0
self_reference_max_shares       0
self_reference_avg_shares       0
LDA_00                          0
LDA_01                          0
LDA_02                          0
LDA_03                          0
LDA_04                          0
global_subjectivity             0
global_sentiment_polarity       0
global_rate_positive_words      0
global_rate_negative_words      0
rate_positive_words             0
rate_negative_words             0
avg_positive_polarity           0
min_positive_polarity           0
max_positive_polarity           0
avg_negative_polarity           0
min_negative_polarity           0
max_negative_polarity           0
title_subjectivity              0
title_sentiment_polarity        0
abs_title_subjectivity          0
abs_title_sentiment_polarity    0
target                          0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.describe()

,id,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,target
count,31715.00000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,...,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000,31715.000000
mean,15857.00000,10.216617,545.006275,0.564569,1.018446,0.705974,11.120132,3.437080,4.734038,1.260728,...,0.097628,0.771429,-0.261620,-0.521061,-0.110094,0.280474,0.074288,0.341994,0.155524,0.547280
std,9155.47623,2.059007,472.320076,3.935137,5.846748,3.648413,11.250545,3.951435,8.618716,4.192666,...,0.072047,0.230525,0.124925,0.283762,0.095831,0.323386,0.264154,0.189209,0.226069,0.497767
min,0.00000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,0.000000
25%,7928.50000,9.000000,245.000000,0.476367,1.000000,0.629921,5.000000,1.000000,1.000000,0.000000,...,0.050000,0.600000,-0.328125,-0.700000,-0.125000,0.000000,0.000000,0.166667,0.000000,0.000000
50%,15857.00000,10.000000,403.000000,0.545455,1.000000,0.694915,8.000000,3.000000,1.000000,0.000000,...,0.100000,0.800000,-0.253819,-0.500000,-0.100000,0.125000,0.000000,0.500000,0.000000,1.000000
75%,23785.50000,12.000000,706.000000,0.614939,1.000000,0.759398,14.000000,4.000000,5.000000,1.000000,...,0.100000,1.000000,-0.187500,-0.300000,-0.050000,0.500000,0.150000,0.500000,0.250000,1.000000
max,31714.00000,19.000000,8474.000000,701.000000,1042.000000,650.000000,187.000000,74.000000,128.000000,91.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,1.000000,1.000000

In [19]:
df.dtypes

id                                int64
publish_date                     object
weekday                          object
channel                          object
n_tokens_title                  float64
n_tokens_content                float64
n_unique_tokens                 float64
n_non_stop_words                float64
n_non_stop_unique_tokens        float64
num_hrefs                       float64
num_self_hrefs                  float64
num_imgs                        float64
num_videos                      float64
average_token_length            float64
num_keywords                    float64
kw_min_min                      float64
kw_max_min                      float64
kw_avg_min                      float64
kw_min_max                      float64
kw_max_max                      float64
kw_avg_max                      float64
kw_min_avg                      float64
kw_max_avg                      float64
kw_avg_avg                      float64
self_reference_min_shares       float64
self_reference_max_shares       float64
self_reference_avg_shares       float64
LDA_00                          float64
LDA_01                          float64
LDA_02                          float64
LDA_03                          float64
LDA_04                          float64
global_subjectivity             float64
global_sentiment_polarity       float64
global_rate_positive_words      float64
global_rate_negative_words      float64
rate_positive_words             float64
rate_negative_words             float64
avg_positive_polarity           float64
min_positive_polarity           float64
max_positive_polarity           float64
avg_negative_polarity           float64
min_negative_polarity           float64
max_negative_polarity           float64
title_subjectivity              float64
title_sentiment_polarity        float64
abs_title_subjectivity          float64
abs_title_sentiment_polarity    float64
target                            int64
dtype: object

In [30]:
df.astype({'target':'int64'}, errors='ignore')

,id,publish_date,weekday,channel,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,target
0,0,2013-01-07,Monday,Entertainment,12.0,219.0,0.663594,1.0,0.815385,4.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,0
1,1,2013-01-07,Monday,Business,9.0,255.0,0.604743,1.0,0.791946,3.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,0
2,2,2013-01-07,Monday,Business,9.0,211.0,0.575130,1.0,0.663866,3.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1
3,3,2013-01-07,Monday,Entertainment,9.0,531.0,0.503788,1.0,0.665635,9.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,0
4,4,2013-01-07,Monday,Tech,13.0,1072.0,0.415646,1.0,0.540890,19.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31710,31710,2014-08-28,Friday,Other,11.0,167.0,0.568493,1.0,0.575472,23.0,...,0.100000,0.8,-0.281731,-0.500,-0.050000,0.650000,0.350000,0.150000,0.350000,1
31711,31711,2014-08-28,Friday,Business,12.0,795.0,0.465736,1.0,0.623246,23.0,...,0.062500,0.9,-0.223264,-0.400,-0.050000,0.000000,0.000000,0.500000,0.000000,1
31712,31712,2014-08-28,Friday,Tech,13.0,1018.0,0.453823,1.0,0.631491,10.0,...,0.050000,0.9,-0.239074,-0.600,-0.050000,0.100000,0.000000,0.400000,0.000000,1
31713,31713,2014-08-28,Friday,Tech,10.0,190.0,0.609626,1.0,0.774775,2.0,...,0.100000,1.0,-1.000000,-1.000,-1.000000,0.000000,0.000000,0.500000,0.000000,1
31714,31714,2014-08-28,Friday,Social Media,12.0,1052.0,0.364971,1.0,0.507488,6.0,...,0.100000,1.0,-0.226603,-0.500,-0.125000,0.485000,0.090000,0.015000,0.090000,1

In [ ]:
def prep(df):
    df = df.copy()
    d = pd.to_datetime(df['publish_date'])       
    df['year'] = d.dt.year
    df['month'] = d.dt.month
    df['day'] = d.dt.day
    df = df.drop(columns=['publish_date'])
    return pd.get_dummies(df, columns=['weekday', 'channel'], dtype=int)

In [75]:
from sklearn.model_selection import train_test_split
y=df['target']
X=df.drop('target', axis=1)

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X = prep(df.drop(columns=['id', 'target']))   
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X, y)

/opt/anaconda3/envs/xgb64/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [77]:
from sklearn.linear_model import LogisticRegression

model= LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)
preds = model.predict_proba(X_test)[:, 1]

/opt/anaconda3/envs/xgb64/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [78]:
from sklearn.preprocessing  import StandardScaler

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [79]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [80]:
y_pred = model.predict(X_test)      # ehtimal yox, 0/1 sinif

print('Accuracy:', accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.5587261548163329
              precision    recall  f1-score   support

           0       0.52      0.58      0.55      2906
           1       0.60      0.54      0.57      3437

    accuracy                           0.56      6343
   macro avg       0.56      0.56      0.56      6343
weighted avg       0.56      0.56      0.56      6343

[[1687 1219]
 [1580 1857]]

/opt/anaconda3/envs/xgb64/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [84]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
rf = RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)                       # scale lazım deyil, X_tr birbaşa verilir

rf_pred = rf.predict(X_test)
rf_proba = rf.predict_proba(X_test)[:, 1]

print('Accuracy:', accuracy_score(y_test, rf_pred))
print('AUC:', roc_auc_score(y_test, rf_proba))
print(classification_report(y_test, rf_pred))
print(confusion_matrix(y_test, rf_pred))

Accuracy: 0.6623049030427243
AUC: 0.71977729701934
              precision    recall  f1-score   support

           0       0.65      0.56      0.60      2906
           1       0.67      0.75      0.71      3437

    accuracy                           0.66      6343
   macro avg       0.66      0.65      0.65      6343
weighted avg       0.66      0.66      0.66      6343

[[1631 1275]
 [ 867 2570]]

In [88]:
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

lgbm = LGBMClassifier(n_estimators=500, learning_rate=0.03, num_leaves=31, random_state=42, verbose=-1)
lgbm.fit(X_train, y_train)

lgbm_pred = lgbm.predict(X_test)
lgbm_proba = lgbm.predict_proba(X_test)[:, 1]

print('Accuracy:', accuracy_score(y_test, lgbm_pred))
print('AUC:', roc_auc_score(y_test, lgbm_proba))
print(classification_report(y_test, lgbm_pred))
print(confusion_matrix(y_test, lgbm_pred))

Accuracy: 0.6725524199905407
AUC: 0.7296974285542077
              precision    recall  f1-score   support

           0       0.66      0.60      0.63      2906
           1       0.68      0.74      0.71      3437

    accuracy                           0.67      6343
   macro avg       0.67      0.67      0.67      6343
weighted avg       0.67      0.67      0.67      6343

[[1736 1170]
 [ 907 2530]]